
<?php include "header.php"?>
        <main>
        <section class="articles container">
            <div class="row">
              <?php foreach($articles as $key=>$value): ?>
                <article class="col-10 offset-1 " >
                  <div class="row">
                    <h1 class="col-6"><?=$value["titre"]?> </h1>
                    <h4 class="col-6"><?=$value["date"]?></h4>
                  </div>
                  <img src="public/images/<?=$value['image']?> " width="50%" alt="">
                  <p><?=substr($value["corps_text"],0,250)?> ...<a href="article.php?id=<?= $value["id"]?> ">Lire la suite</a> </p>
                  <hr class=" clear my-4">

                </article>
              <?php endforeach; ?>
            </div>
        </section>
      </main>
<?php include "footer.php"?>
